version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - DATABASE_URL=bookmarks.db
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
    volumes:
      - backend-data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api/v1
    stdin_open: true

volumes:
  backend-data: